# Jason Solano Fonseca

# Como importar Pandas

Tambien utilizamos el numpy una libreria muy utilizada en data science

In [3]:
import pandas as pd
import numpy as np

# Como Cargar un archivo

Se Puede cargar diferentes tipos de archivo por ejemplo .csv o .xlsx.

Tambien se pueden leer archivos en .json

In [9]:
# leer csv
datasetCSV = pd.read_csv('https://raw.githubusercontent.com/fmezacr/DataScienceTEC/master/Clase2/pima-indians-diabetes.csv')
# leer xlsx
datasetXLSX = pd.read_excel('https://sds-platform-private.s3-us-east-2.amazonaws.com/uploads/P1-OfficeSupplies.xlsx')
# leer json
datasetJson = pd.read_json('https://raw.githubusercontent.com/jdorfman/awesome-json-datasets/master/package.json')

# Seguiremos con el datasetCSV

Formas de leer un dataset

In [11]:
datasetCSV

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
5     3   78  50  32   88  31.0  0.248  26  1
6    10  115   0   0    0  35.3  0.134  29  0
7     2  197  70  45  543  30.5  0.158  53  1
8     8  125  96   0    0   0.0  0.232  54  1
9     4  110  92   0    0  37.6  0.191  30  0
10   10  168  74   0    0  38.0  0.537  34  1
11   10  139  80   0    0  27.1  1.441  57  0
12    1  189  60  23  846  30.1  0.398  59  1
13    5  166  72  19  175  25.8  0.587  51  1
14    7  100   0   0    0  30.0  0.484  32  1
15    0  118  84  47  230  45.8  0.551  31  1
16    7  107  74   0    0  29.6  0.254  31  1
17    1  103  30  38   83  43.3  0.183  33  0
18    1  115  70  30   96  34.6  0.529  32  1
19    3  126  88  41  235  39.3  0.704  27  0
20    8   99  84   0    0  35.4  0.388  50  0
21    7  196  90   0    0  39.8  0.451  41  1
22    9  119  80  35    0  29.0  0.263  29  1
23   11  143  94  33  146  36.6  0.254  51  1
24   10  125  70  26  115  31.1  0.205  41  1
25    7  147  76   0    0  39.4  0.257  43  1
26    1   97  66  15  140  23.2  0.487  22  0
27   13  145  82  19  110  22.2  0.245  57  0
28    5  117  92   0    0  34.1  0.337  38  0
29    5  109  75  26    0  36.0  0.546  60  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
737   2   99  60  17  160  36.6  0.453  21  0
738   1  102  74   0    0  39.5  0.293  42  1
739  11  120  80  37  150  42.3  0.785  48  1
740   3  102  44  20   94  30.8  0.400  26  0
741   1  109  58  18  116  28.5  0.219  22  0
742   9  140  94   0    0  32.7  0.734  45  1
743  13  153  88  37  140  40.6  1.174  39  0
744  12  100  84  33  105  30.0  0.488  46  0
745   1  147  94  41    0  49.3  0.358  27  1
746   1   81  74  41   57  46.3  1.096  32  0
747   3  187  70  22  200  36.4  0.408  36  1
748   6  162  62   0    0  24.3  0.178  50  1
749   4  136  70   0    0  31.2  1.182  22  1
750   1  121  78  39   74  39.0  0.261  28  0
751   3  108  62  24    0  26.0  0.223  25  0
752   0  181  88  44  510  43.3  0.222  26  1
753   8  154  78  32    0  32.4  0.443  45  1
754   1  128  88  39  110  36.5  1.057  37  1
755   7  137  90  41    0  32.0  0.391  39  0
756   0  123  72   0    0  36.3  0.258  52  1
757   1  106  76   0    0  37.5  0.197  26  0
758   6  190  92   0    0  35.5  0.278  66  1
759   2   88  58  26   16  28.4  0.766  22  0
760   9  170  74  31    0  44.0  0.403  43  1
761   9   89  62   0    0  22.5  0.142  33  0
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

Evitando los encabezados e indices

In [13]:
datasetCSV = pd.read_csv('https://raw.githubusercontent.com/fmezacr/DataScienceTEC/master/Clase2/pima-indians-diabetes.csv',header=None)
datasetCSV

      0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
5     5  116  74   0    0  25.6  0.201  30  0
6     3   78  50  32   88  31.0  0.248  26  1
7    10  115   0   0    0  35.3  0.134  29  0
8     2  197  70  45  543  30.5  0.158  53  1
9     8  125  96   0    0   0.0  0.232  54  1
10    4  110  92   0    0  37.6  0.191  30  0
11   10  168  74   0    0  38.0  0.537  34  1
12   10  139  80   0    0  27.1  1.441  57  0
13    1  189  60  23  846  30.1  0.398  59  1
14    5  166  72  19  175  25.8  0.587  51  1
15    7  100   0   0    0  30.0  0.484  32  1
16    0  118  84  47  230  45.8  0.551  31  1
17    7  107  74   0    0  29.6  0.254  31  1
18    1  103  30  38   83  43.3  0.183  33  0
19    1  115  70  30   96  34.6  0.529  32  1
20    3  126  88  41  235  39.3  0.704  27  0
21    8   99  84   0    0  35.4  0.388  50  0
22    7  196  90   0    0  39.8  0.451  41  1
23    9  119  80  35    0  29.0  0.263  29  1
24   11  143  94  33  146  36.6  0.254  51  1
25   10  125  70  26  115  31.1  0.205  41  1
26    7  147  76   0    0  39.4  0.257  43  1
27    1   97  66  15  140  23.2  0.487  22  0
28   13  145  82  19  110  22.2  0.245  57  0
29    5  117  92   0    0  34.1  0.337  38  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
738   2   99  60  17  160  36.6  0.453  21  0
739   1  102  74   0    0  39.5  0.293  42  1
740  11  120  80  37  150  42.3  0.785  48  1
741   3  102  44  20   94  30.8  0.400  26  0
742   1  109  58  18  116  28.5  0.219  22  0
743   9  140  94   0    0  32.7  0.734  45  1
744  13  153  88  37  140  40.6  1.174  39  0
745  12  100  84  33  105  30.0  0.488  46  0
746   1  147  94  41    0  49.3  0.358  27  1
747   1   81  74  41   57  46.3  1.096  32  0
748   3  187  70  22  200  36.4  0.408  36  1
749   6  162  62   0    0  24.3  0.178  50  1
750   4  136  70   0    0  31.2  1.182  22  1
751   1  121  78  39   74  39.0  0.261  28  0
752   3  108  62  24    0  26.0  0.223  25  0
753   0  181  88  44  510  43.3  0.222  26  1
754   8  154  78  32    0  32.4  0.443  45  1
755   1  128  88  39  110  36.5  1.057  37  1
756   7  137  90  41    0  32.0  0.391  39  0
757   0  123  72   0    0  36.3  0.258  52  1
758   1  106  76   0    0  37.5  0.197  26  0
759   6  190  92   0    0  35.5  0.278  66  1
760   2   88  58  26   16  28.4  0.766  22  0
761   9  170  74  31    0  44.0  0.403  43  1
762   9   89  62   0    0  22.5  0.142  33  0
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

Pasar un dataset a matrix de numpy

In [15]:
matrix = datasetCSV.as_matrix()
matrix

/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

Obtener los primeros y ultimos elementos

Tambien Aplicable para cada columna

In [17]:
datasetCSV.head(5)

   0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [18]:
datasetCSV.tail(5)

      0    1   2   3    4     5      6   7  8
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

Descripcion de el data set

In [19]:
datasetCSV.describe()

,0,1,2,3,4,5,6,7,8
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Acceder a cada columna y valores

In [23]:
datasetCSV[0]

0       6
1       1
2       8
3       1
4       0
5       5
6       3
7      10
8       2
9       8
10      4
11     10
12     10
13      1
14      5
15      7
16      0
17      7
18      1
19      1
20      3
21      8
22      7
23      9
24     11
25     10
26      7
27      1
28     13
29      5
       ..
738     2
739     1
740    11
741     3
742     1
743     9
744    13
745    12
746     1
747     1
748     3
749     6
750     4
751     1
752     3
753     0
754     8
755     1
756     7
757     0
758     1
759     6
760     2
761     9
762     9
763    10
764     2
765     5
766     1
767     1
Name: 0, Length: 768, dtype: int64

In [24]:
datasetCSV[0][0]

6

In [25]:
datasetCSV[0][0] = 1

/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [26]:
datasetCSV.head(1)

   0    1   2   3  4     5      6   7  8
0  1  148  72  35  0  33.6  0.627  50  1

Acceder a una fila

In [39]:
datasetCSV.iloc[0]

0      1.000
1    148.000
2     72.000
3     35.000
4      0.000
5     33.600
6      0.627
7     50.000
8      1.000
Name: 0, dtype: float64

In [40]:
datasetCSV.iloc[0,:]

0      1.000
1    148.000
2     72.000
3     35.000
4      0.000
5     33.600
6      0.627
7     50.000
8      1.000
Name: 0, dtype: float64

In [41]:
datasetCSV.iloc[:,0]

0       1
1       1
2       8
3       1
4       0
5       5
6       3
7      10
8       2
9       8
10      4
11     10
12     10
13      1
14      5
15      7
16      0
17      7
18      1
19      1
20      3
21      8
22      7
23      9
24     11
25     10
26      7
27      1
28     13
29      5
       ..
738     2
739     1
740    11
741     3
742     1
743     9
744    13
745    12
746     1
747     1
748     3
749     6
750     4
751     1
752     3
753     0
754     8
755     1
756     7
757     0
758     1
759     6
760     2
761     9
762     9
763    10
764     2
765     5
766     1
767     1
Name: 0, Length: 768, dtype: int64

Renombrar columnas

In [48]:
datasetCSV = pd.read_csv('https://raw.githubusercontent.com/fmezacr/DataScienceTEC/master/Clase2/pima-indians-diabetes.csv')

In [53]:
datasetCSV.shape

(767, 9)

In [58]:
datasetCSV = datasetCSV.rename(columns={'6': 'Veces Embarazada', '148': 'Glucosa','72':'P Sanguinia','35':'G Cutaneos','0':'Insulina','33.6':'M Corporal','0.627':'Herencia','50':'Edad','1':'Resultado'})

Uso de condicionales

In [63]:
datasetCSV.loc[(datasetCSV.Edad == 30)]

,Veces Embarazada,Glucosa,P Sanguinia,G Cutaneos,Insulina,M Corporal,Herencia,Edad,Resultado
4,5,116,74,0,0,25.6,0.201,30,0
9,4,110,92,0,0,37.6,0.191,30,0
51,5,88,66,21,23,24.4,0.342,30,0
125,3,120,70,30,135,42.9,0.452,30,0
131,3,170,64,37,225,34.5,0.356,30,1
255,3,111,56,39,0,30.1,0.557,30,0
299,0,167,0,0,0,32.3,0.839,30,1
308,2,124,68,28,205,32.9,0.875,30,1
315,3,99,80,11,64,19.3,0.284,30,0
325,1,122,64,32,156,35.1,0.692,30,1
350,4,137,84,0,0,31.2,0.252,30,0
363,4,147,74,25,293,34.9,0.385,30,0
364,5,99,54,28,83,34.0,0.499,30,0
443,4,117,62,12,0,29.7,0.380,30,1
495,5,110,68,0,0,26.0,0.292,30,0
555,1,97,70,40,0,38.1,0.218,30,0
601,1,124,74,36,0,27.8,0.100,30,0
615,6,117,96,0,0,28.7,0.157,30,0
644,2,157,74,35,440,39.4,0.134,30,0
705,10,115,0,0,0,0.0,0.261,30,1
764,5,121,72,23,112,26.2,0.245,30,0

Operaciones con dataframe

In [68]:
datasetCSV.Edad.sum()

25479

In [69]:
datasetCSV.Insulina.mean()

79.90352020860496

In [70]:
datasetCSV.Glucosa.std()

31.978468455767796

Transformar dataframe

In [73]:
datasetCSV.to_json('dataset.json')